
const gateDeviceDistribution = {
    'Main Gate': {'Automatic Tyre Killer': 1,'UVSS': 2,'Bollards': 8,'Boom Barrier': 4,'Swing Barriers': 8,'Visitor Kiosks': 3,'32" Overhead Display': 3,'Indoor Digital Displays': 2,'Outdoor Digital Displays': 3,'DFMD': 6,'Baggage Scanner': 2,'Frisking Booth': 1,'Long Range RFID Reader': 8,'Push Button for Boom Barrier': 8,'EM Locks': 3,'Indoor Dome - 5 MP': 35,'Outdoor Fixed - 5 MP': 26,'PTZ with IR - 2MP': 2,'Panoramic - 180 - 20 MP': 1,'Panoramic - 360 - 20 MP': 8,'ANPR Cameras': 4,'Face recognition Cameras': 4,'IP Horn Speaker': 31,'IP Ceiling Speaker': 28,'Face recognition Readers': 14,'Smart Card Reader': 1,'QR Code Readers': 14,'Camera Poles': 4,'Rack (12U)': 2,'Outdoor Junction Box': 16,'Portable face readers (on gates)': 4,'10 finger enrolment readers': 2,'Indoor signages': 10},
    'LP Gate': {'Automatic Tyre Killer': 1,'Manual Tyre Killer': 1,'Bollards': 8,'Boom Barrier': 4,'Swing Barriers': 4,'Visitor Kiosks': 1,'32" Overhead Display': 2,'Indoor Digital Displays': 1,'Outdoor Digital Displays': 2,'DFMD': 1,'Baggage Scanner': 1,'Frisking Booth': 1,'Long Range RFID Reader': 4,'Push Button for Boom Barrier': 4,'EM Locks': 2,'Indoor Dome - 5 MP': 10,'Outdoor Fixed - 5 MP': 11,'Panoramic - 180 - 20 MP': 1,'Panoramic - 360 - 20 MP': 2,'ANPR Cameras': 2,'Face recognition Cameras': 2,'IP Horn Speaker': 5,'IP Ceiling Speaker': 5,'Face recognition Readers': 4,'Smart Card Reader': 1,'QR Code Readers': 4,'Camera Poles': 4,'Rack (12U)': 1,'10 finger enrolment readers': 1,'Indoor signages': 6},
    'Jokatte Gate': {'Automatic Tyre Killer': 1,'Manual Tyre Killer': 1,'UVSS': 2,'Bollards': 8,'Boom Barrier': 4,'Swing Barriers': 3,'Visitor Kiosks': 1,'32" Overhead Display': 2,'Indoor Digital Displays': 2,'Outdoor Digital Displays': 3,'DFMD': 2,'Baggage Scanner': 2,'Frisking Booth': 1,'Long Range RFID Reader': 4,'Push Button for Boom Barrier': 4,'EM Locks': 2,'Indoor Dome - 5 MP': 23,'Outdoor Fixed - 5 MP': 14,'PTZ with IR - 2MP': 2,'Panoramic - 180 - 20 MP': 2,'Panoramic - 360 - 20 MP': 3,'ANPR Cameras': 4,'Face recognition Cameras': 4,'IP Horn Speaker': 9,'IP Ceiling Speaker': 2,'Face recognition Readers': 6,'Smart Card Reader': 2,'QR Code Readers': 6,'Camera Poles': 2,'Rack (12U)': 1,'Outdoor Junction Box': 17,'10 finger enrolment readers': 1,'Indoor signages': 10,'Wireless Access Point': 1},
    'E2 Gate': {'Boom Barrier': 2,'Swing Barriers': 2,'32" Overhead Display': 2,'Indoor Digital Displays': 1,'DFMD': 2,'Baggage Scanner': 1,'Frisking Booth': 1,'Long Range RFID Reader': 2,'Push Button for Boom Barrier': 2,'EM Locks': 1,'Indoor Dome - 5 MP': 4,'Outdoor Fixed - 5 MP': 3,'PTZ with IR - 2MP': 2,'Panoramic - 180 - 20 MP': 2,'Panoramic - 360 - 20 MP': 2,'ANPR Cameras': 2,'Face recognition Cameras': 3,'IP Horn Speaker': 1,'IP Ceiling Speaker': 1,'Face recognition Readers': 4,'QR Code Readers': 4,'Camera Poles': 2,'Rack (12U)': 1,'Outdoor Junction Box': 14,'Indoor signages': 2,'Wireless Access Point': 1},
    'PCR': {'Video Wall (2 by 3)': 1,'Indoor Dome - 5 MP': 2,'Outdoor Fixed - 5 MP': 2,'Face recognition Cameras': 2,'IP Horn Speaker': 2,'IP Ceiling Speaker': 2,'Master & Local Control Desks': 1},
    'Railway Siding': {'Boom Barrier': 2,'ANPR Cameras': 2,'Indoor Dome - 5 MP': 2,'Outdoor Fixed - 5 MP': 6},
    'Cargo Gate': {'Automatic Tyre Killer': 1,'Manual Tyre Killer': 1,'UVSS': 2,'Bollards': 8,'Boom Barrier': 4,'Swing Barriers': 4,'Visitor Kiosks': 2,'32" Overhead Display': 3,'Indoor Digital Displays': 4,'Outdoor Digital Displays': 3,'Video Wall (6 by 3)': 1,'DFMD': 2,'Baggage Scanner': 1,'Frisking Booth': 2,'Long Range RFID Reader': 6,'Push Button for Boom Barrier': 3,'Indoor Dome - 5 MP': 16,'Outdoor Fixed - 5 MP': 6,'PTZ with IR - 2MP': 2,'ANPR Cameras': 4,'Face recognition Cameras': 4,'IP Horn Speaker': 5,'IP Ceiling Speaker': 2,'Camera Poles': 3,'Rack (12U)': 1},
    'CISF Checking': {'Video Wall (2 by 3)': 1,'DFMD': 2,'Baggage Scanner': 1,'Frisking Booth': 1,'ANPR Cameras': 2,'Face recognition Cameras': 2}
};
